source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "puma", ">= 5.0"
gem "mongoid", "~> 9.0"
gem "dotenv-rails"
gem "twilio-ruby"
gem "sidekiq"
gem "rack-cors"
gem "rack-attack"
gem "lograge"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
